### ISSUE TITLE
organizations returns nothing on the body

### ISSUE THREAD

**Issue by legion49f** [ddexterpark/dashboard-api-golang#1]
# Expected Behavior

Please describe the behavior you are expecting

I am expecting a list of organizations to which i have access to.

# Current Behavior

What is the current behavior?

Response body is nil

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
package main

import (
	"fmt"
	"io"
	"io/ioutil"

	// "github.com/ddexterpark/dashboard-api-golang/api"
	// "github.com/aws/aws-sdk-go/service/organizations"

	"github.com/ddexterpark/dashboard-api-golang/api/general/organizations/configure"
	// "github.com/ddexterpark/dashboard-api-golang/general/organizations/configure"
	// "github.com/ddexterpark/dashboard-api-golang/api"
)

func readBody(r io.ReadCloser) ([]byte, error) {
	body, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}
	defer r.Close()
	return body, nil
}

func main() {
	fmt.Println("test")
	mk := configure.GetOrganizations()

	for _, a := range mk {
		// b, err := readBody(a)
		// if err != nil {
		// 	fmt.Println(err)
		// 	return
		// }
		// fmt.Println(string(b))
		fmt.Println(a)
	}
}
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Geo Location:  NC, united states
* Operating System: MacOS
* Special Network Conditions: N/A

## Failure Logs

Please include any relevant log snippets or files here.
{{GET https://api.meraki.com/v1/organizations  <nil> v1} {200 OK 200 HTTP/1.1 1 1 map[Cache-Control:[max-age=0, private, must-revalidate] Content-Security-Policy:[default-src 'self' data: https://*.typekit.net https://*.typekit.com https://csi.gstatic.com https://www.google.com https://hcaptcha.com https://*.hcaptcha.com;  style-src 'self' 'unsafe-inline' https://use.typekit.com https://hcaptcha.com https://*.hcaptcha.com;  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://use.typekit.com/ https://maps.googleapis.com https://www.google.com https://www.gstatic.com https://hcaptcha.com https://*.hcaptcha.com; report-uri /nmr/browser_metrics/log_csp_report] Content-Type:[application/json; charset=utf-8] Date:[Thu, 10 Jun 2021 13:27:00 GMT] Etag:["3c86a8e7a50798686c4c2b35980327d8"] Server:[nginx/1.19.10] Vary:[Accept-Encoding] X-Frame-Options:[sameorigin] X-Request-Id:[4e2b1ce895c7cd6fcb789e5d2da042e6] X-Runtime:[0.010368] X-Ua-Compatible:[IE=Edge,chrome=1] X-Xss-Protection:[1; mode=block]]} [] map[mode:login]}

Would you be ok with me working to fix this and some of the other bugs I've found and PR this ?

**Comment by iamdexterpark** [comment]
Thank you very much for submitting this bug, and for the kind offer of PR's. I'm more than happy to peer review and accept any PR that you would be willing to put your time and effort into making. If you feel confident in resolving this issue you have my appreciation, otherwise, you have my commitment to get it resolved. Thanks again!

**Comment by iamdexterpark** [comment]
So after reviewing this it looks like our goal is to retrieve a list of organizations using the Meraki GoLang library. I was able to achieve this using the following code sample: 

**Set  Environmental Variables**
```
export MERAKI_DASHBOARD_API_KEY=*********************
export MERAKI_DASHBOARD_API_URL=https://api.meraki.com/api/
```


**Go Script**

```
package main

import (
	"github.com/ddexterpark/dashboard-api-golang/api/general/organizations/configure"
	"github.com/kr/pretty"
)

func main() {

	// Get list of Meraki Organizations
	mk := configure.GetOrganizations()
	for _, metadata := range mk {
		_, _ = pretty.Println(metadata.Payload)
	}
}
```

One thing that I want to point out is that this library already has an HTTP client built-in and passes data through a strongly typed interface containing a verbose output of the session. In this example, I am just printing the payload which is a struct that corresponds to the format of the Meraki Dashboard API call which looks like this:

**Organization Data Model**
```
type Organization struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Organizations []struct {
	Organization
}
```

I think that should resolve your issue, in this case, it may not be necessary to call "io/ioutil". I'm marking this as closed but if for some reason this does not address your issue please let me know and I'll be happy to reopen.

**Comment by provector** [comment]
I was trying to follow the above example to get some organizations results. While the printing works fine, the GetOrganizations() function (like any other for that matter) returns []api.Results, and the "Payload" inside is an interface, not the desired struct. I was trying to do type assertion but that fails at runtime. The only way I found to convert Payload interface to Organizations struct (or any other for that matter) is to marshal it to a json string and then unmarshal to a proper struct. Is there any recommended way of doing it? Any help on the matter would be greatly appreciated.

**Comment by iamdexterpark** [comment]
> I was trying to follow the above example to get some organizations results. While the printing works fine, the GetOrganizations() function (like any other for that matter) returns []api.Results, and the "Payload" inside is an interface, not the desired struct. I was trying to do type assertion but that fails at runtime. The only way I found to convert Payload interface to Organizations struct (or any other for that matter) is to marshal it to a json string and then unmarshal to a proper struct. Is there any recommended way of doing it? Any help on the matter would be greatly appreciated.

First off thank you for your input. You are right, type assertion will not work as this requires marshalling and unmarshalling into the proper structure. I do not have a solution to this at present but I take all feature requests seriously and will look at best practices to see what a refactor might look like. Appreciate you!

**Comment by provector** [comment]
Hey! Also thanks for putting time into this library :) It saved me a lot of time writing my own API. I did some more research and unfortunately like you said it's not possible in the current version of go. There's an experimental feature for generics (like in Java) in go2, so hopefully in a couple of years that will become a standard. This way I could see how easily we could write a function that based on generics populates appropriate structure upon reading. I'll be working with Your library extensively for the next month (due to the project I'm involved in) so I'll make sure to post any feedback.
